name_conversion = {
    "MaternalAge": "m_age",
    "MaternalHeight": "m_height",
    "MaternalWeight": "m_weight",
    "Gender": "gender",
    "PregestationalDiabetes": "diabetes_0",
    "GestationalDiabetes": "diabetes_1",
    "Smoking": "smoking",
    "PlacentaSite": "placenta_site",
    "AmnioticFluid": "af",
    "LastPregnancySga": "last_preg_sga",
    "LastPregnancyFgr": "last_preg_fgr",
    "LastPregnancyNormal": "last_preg_normal",
    "PreviousFailedPregnancy": "prev_failed_preg",
    "HighRiskPretermPreeclampsia": "high_risk_pe",
    "GestationalAge": "ga",
    "BiparietalDiameter": "bpd",
    "HeadCircumference": "hc",
    "AbdominalCircumference": "ac",
    "FemurLength": "fl",
    "UterineArteryResistanceIndex": "ute_ari",
    "UterineArteryPulsatilityIndex": "ute_api",
    "CerebroplacentalRatio": "cpr",
    "MiddleCerebralArteryPeakSystolicVelocity": "psv",
    "EstimatedFetalWeight": "efw",
    "UmbilicalArterialPulsatilityIndex": "umb_api",
}

value_mappings = {
    "gender": {"Male": 0, "Female": 1},
    "placenta_site": {
        "Anterior Placenta": 0,
        "Fundal Placenta": 1,
        "Lateral Placenta": 2,
        "Placenta Previa": 3,
        "Posterior Placenta": 4,
    },
    "af":{
        "Oligohydramnios": 0,
        "Normal": 1,
        "Polyhydramnios": 2,
    },
    "last_preg_sga": {"true": 0, "false": 1},
    "last_preg_fgr": {"true": 0, "false": 1},
    "last_preg_normal": {"true": 0, "false": 1},
    "prev_failed_preg": {"true": 0, "false": 1},
    "high_risk_pe": {"true": 0, "false": 1},
    "diabetes_0": {"true": 0, "false": 1},
    "diabetes_1": {"true": 0, "false": 1},
    "smoking": {"true": 0, "false": 1},
}
